name: CI/CD Pipeline for Python App on EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests (Optional)
        run: |
          pytest || echo "No tests found"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the project directory
            cd /home/ubuntu/mypythonapp

            # Pull the latest changes
            git pull origin main

            # Activate the virtual environment
            source /home/ubuntu/mypythonapp/myenv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Kill existing Gunicorn process (if running)
            pkill gunicorn || echo "Gunicorn was not running"

            # Start Gunicorn in the background with nohup
            nohup gunicorn --bind 0.0.0.0:8000 app:app > /home/ubuntu/mypythonapp/app.log 2>&1 &

            echo "Python application started successfully!"
